CFLAGS = -Wall -Og  -I../boot-check -Werror -std=gnu99
CC = gcc

PROGS = select-ex demand-ex pipe-ex signal-ex pipe-read-exit-ex wait-ex local-socket is-fd-open socket-ex test-redirect dup2-redirect kill-ex
all : $(PROGS)

kill-ex: kill-ex.o
	$(CC) $(CFLAGS) $^ -o $@ -lm

local-socket: local-socket.o
	$(CC) $(CFLAGS) $^ -o $@ -lm

dup2-redirect: dup2-redirect.o
	$(CC) $(CFLAGS) $^ -o $@ -lm

test-redirect: test-redirect.o
	$(CC) $(CFLAGS) $^ -o $@ -lm

is-fd-open: is-fd-open.o
	$(CC) $(CFLAGS) $^ -o $@ -lm

select-ex: select-ex.o
	$(CC) $(CFLAGS) $^ -o $@ -lm

demand-ex: demand-ex.o
	$(CC) $(CFLAGS) $^ -o $@ -lm

pipe-ex: pipe-ex.o
	$(CC) $(CFLAGS) $^ -o $@ -lm

pipe-read-exit-ex: pipe-read-exit-ex.o
	$(CC) $(CFLAGS) $^ -o $@ -lm

signal-ex: signal-ex.o
	$(CC) $(CFLAGS) $^ -o $@ -lm

wait-ex: wait-ex.o
	$(CC) $(CFLAGS) $^ -o $@ -lm

run:
	./dup2-redirect ./test-redirect

clean :
	rm -f *.o *~ Makefile.bak $(PROGS)

depend:
	makedepend *.[ch] 
