# simple example of how to use the template.mk

MAKEFLAGS +=  --no-print-directory

ifndef CS140E_PATH
$(error CS140E_PATH not defined!)
endif

MK = $(CS140E_PATH)/template.mk

all: hello

hello:
	make -f $(MK) NAME=hello

clean:
	make -f $(MK) clean

.PHONY: all hello clean
